import { slate } from "tailwindcss/colors";
import { fontFamily as _fontFamily } from "tailwindcss/defaultTheme";

export default {
  content: [
    "./apps/app/src/**/*.{js,ts,jsx,tsx}",
    "./apps/app/index.html",
    "./apps/landing/src/**/*.{js,ts,jsx,tsx}",
    "./apps/landing/index.html",
    "./apps/config-admin/src/**/*.{js,ts,jsx,tsx}",
    "./apps/config-admin/index.html",
    "./apps/shared/**/*.{js,ts,jsx,tsx}",
    "./packages/ui/**/*.{js,ts,jsx,tsx}",
  ],
  // Safelist for dynamically generated grid column classes (responsive grid view)
  safelist: ["grid-cols-1", "grid-cols-2", "grid-cols-3", "grid-cols-4"],
  darkMode: "class",
  important: true,
  theme: {
    extend: {
      animation: {
        "spin-slow": "spin 3s linear infinite",
      },
      colors: {
        gray: slate,
        pink: {
          10: "#fcfafb",
        },
        purple: {
          10: "#fbfafc",
        },
        border: "rgb(var(--border))",
        input: "rgb(var(--input))",
        ring: "rgb(var(--ring))",
        background: "rgb(var(--background))",
        foreground: "rgb(var(--foreground))",
        primary: {
          100: "rgb(var(--primary-100))",
          200: "rgb(var(--primary-200))",
          300: "rgb(var(--primary-300))",
          400: "rgb(var(--primary-400))",
          50: "rgb(var(--primary-50))",
          500: "rgb(var(--primary-500))",
          600: "rgb(var(--primary-600))",
          700: "rgb(var(--primary-700))",
          800: "rgb(var(--primary-800))",
          900: "rgb(var(--primary-900))",
          950: "rgb(var(--primary-950))",
          DEFAULT: "rgb(var(--primary))",
          foreground: "rgb(var(--primary-foreground))",
        },
        accent: {
          100: "rgb(var(--accent-100))",
          200: "rgb(var(--accent-200))",
          300: "rgb(var(--accent-300))",
          400: "rgb(var(--accent-400))",
          50: "rgb(var(--accent-50))",
          500: "rgb(var(--accent-500))",
          600: "rgb(var(--accent-600))",
          700: "rgb(var(--accent-700))",
          800: "rgb(var(--accent-800))",
          900: "rgb(var(--accent-900))",
          950: "rgb(var(--accent-950))",
          DEFAULT: "rgb(var(--accent))",
          foreground: "rgb(var(--accent-foreground))",
        },
        secondary: {
          50: "rgb(var(--secondary-50))",
          100: "rgb(var(--secondary-100))",
          200: "rgb(var(--secondary-200))",
          300: "rgb(var(--secondary-300))",
          400: "rgb(var(--secondary-400))",
          500: "rgb(var(--secondary-500))",
          600: "rgb(var(--secondary-600))",
          700: "rgb(var(--secondary-700))",
          800: "rgb(var(--secondary-800))",
          900: "rgb(var(--secondary-900))",
          950: "rgb(var(--secondary-950))",
          DEFAULT: "rgb(var(--secondary))",
          foreground: "rgb(var(--secondary-foreground))",
        },
        warning: {
          50: "rgb(var(--warning-50))",
          100: "rgb(var(--warning-100))",
          200: "rgb(var(--warning-200))",
          300: "rgb(var(--warning-300))",
          400: "rgb(var(--warning-400))",
          500: "rgb(var(--warning-500))",
          600: "rgb(var(--warning-600))",
          700: "rgb(var(--warning-700))",
          800: "rgb(var(--warning-800))",
          900: "rgb(var(--warning-900))",
          950: "rgb(var(--warning-950))",
        },
        destructive: {
          DEFAULT: "rgb(var(--destructive))",
          foreground: "rgb(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "rgb(var(--muted))",
          foreground: "rgb(var(--muted-foreground))",
        },
        popover: {
          DEFAULT: "rgb(var(--popover))",
          foreground: "rgb(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "rgb(var(--card))",
          foreground: "rgb(var(--card-foreground))",
        },
        "surface-ground": "rgb(var(--surface-ground))",
        "card-ground": "rgb(var(--card-ground))",
        "footer-ground": "rgb(var(--footer-ground))",
        "header-ground": "rgb(var(--header-ground))",
        "hover-header-ground": "rgb(var(--hover-header-ground))",
        "surface-border": "rgb(var(--surface-border))",
        "modal-card-ground": "rgb(var(--modal-card-ground))",
        "sub-header-color": "rgb(var(--sub-header-color))",
        "even-card-ground": "rgb(var(--even-card-ground))",
        "sub-header-active": "rgb(var(--sub-header-active))",
        "primary-hover": "rgb(var(--primary-hover))",
        "hover-card-ground": "rgb(var(--hover-card-ground))",
        "focus-card-ground": "rgb(var(--focus-card-ground))",
      },
      fontFamily: {
        mono: ['"Roboto Mono"', ..._fontFamily.mono],
        sans: ['"Nunito"', '"Roboto"', ..._fontFamily.sans],
      },
      spacing: {
        0.75: "0.1875rem",
        13: "3.25rem",
        15: "3.75rem",
        18: "4.5rem",
        21: "5.25rem",
        22: "5.5rem",
        26: "6.5rem",
        27: "6.75rem",
        30: "7.5rem",
        34: "8.4rem",
        39: "9.8rem",
        45: "11.2rem",
        50: "12.5rem",
        57: "14.25rem",
        58: "14.5rem",
        59: "14.65rem",
        62: "15.5rem",
        66: "16.5rem",
        67: "16.79rem",
        68: "17rem",
        70: "17.5rem",
        74: "19.438rem",
        90: "22.5rem",
        100: "25rem",
        105: "26rem",
        110: "27rem",
        113: "27.5rem",
        115: "28rem",
        120: "30rem",
        128: "32rem",
        140: "35rem",
        160: "40rem",
        165: "41.5rem",
        180: "45rem",
        185: "46.5rem",
        192: "48rem",
        200: "50rem",
        240: "60rem",
        256: "64rem",
        280: "70rem",
        320: "80rem",
        360: "90rem",
        400: "100rem",
        480: "120rem",
      },
      zIndex: {
        "-1": -1,
        49: 49,
        60: 60,
        70: 70,
        80: 80,
        90: 90,
        99: 99,
        999: 999,
        9999: 9999,
        99999: 99999,
      },
      fontSize: {
        xs: "0.625rem",
        sm: "0.75rem",
        md: "0.8125rem",
        base: "0.875rem",
        lg: "1rem",
        xl: "1.125rem",
        "2xl": "1.25rem",
        "3xl": "1.5rem",
        "4xl": "2rem",
        "5xl": "2.25rem",
        "6xl": "2.5rem",
        "7xl": "3rem",
        "7.5xl": "3.5rem",
        "8xl": "4rem",
        "9xl": "6rem",
        "10xl": "8rem",
      },
      screens: {
        sm: "640px", // Native Tailwind
        md: "768px", // Native Tailwind
        lg: "1024px", // Native Tailwind
        xl: "1280px", // Native Tailwind
        "2xl": "1536px", // Native Tailwind
        "3xl": "1920px", // Custom for ultra-wide screens
      },
      opacity: {
        12: "0.12",
        38: "0.38",
        87: "0.87",
      },
      scale: {
        "-1": "-1",
      },
      flex: {
        0: "0 0 auto",
      },
      rotate: {
        "-270": "270deg",
        15: "15deg",
        30: "30deg",
        60: "60deg",
        270: "270deg",
      },
      transitionDuration: {
        400: "400ms",
      },
      transitionTimingFunction: {
        drawer: "cubic-bezier(0.25, 0.8, 0.25, 1)",
      },
      maxHeight: {
        none: "none",
      },
      minHeight: {},
      minWidth: {
        screen: "100vw",
      },
      maxWidth: {
        screen: "100vw",
        "7xl": "80rem",
        "8xl": "88rem",
        "9xl": "96rem",
        "10xl": "104rem",
        "11xl": "112rem",
      },
    },
  },
  plugins: [
    require("@tailwindcss/typography")({ modifiers: ["sm", "lg"] }),
    require("@tailwindcss/aspect-ratio"),
    // Якщо є ще плагіни — додавай за потреби
  ],
};
